kind: Deployment
apiVersion: apps/v1
metadata:
  name: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: tonghuntz/tharasri
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      restartPolicy: Always
---

kind: Service
apiVersion: v1
metadata:
  name: test
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      nodePort: 31000
  selector:
    app: test